"use client";
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Loader2} from 'lucide-react';
export default function AgentVoice({disabled,onText,tokenFetch}:{disabled:boolean;onText:(text:string)=>void;tokenFetch:(url:string,init:RequestInit)=>Promise<Response>}){
 const [recording,setRecording]=useState(false),[busy,setBusy]=useState(false),[note,setNote]=useState('');
 const recognition=useRef<any>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),mounted=useRef(true),cancelled=useRef(false);
 function release(){if(timer.current)clearTimeout(timer.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;cancelled.current=true;recognition.current?.abort();if(recorder.current?.state==='recording')recorder.current.stop();release();};},[]);
 async function record(){if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setNote('이 환경에서는 음성 녹음을 지원하지 않습니다. 키보드로 입력해주세요.');return;}cancelled.current=false;try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){release();return;}const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(x=>MediaRecorder.isTypeSupported(x));const r=new MediaRecorder(stream.current,mime?{mimeType:mime}:undefined);recorder.current=r;const chunks:Blob[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=async()=>{release();if(!mounted.current||cancelled.current)return;setRecording(false);setBusy(true);setNote('음성을 글자로 바꾸는 중입니다…');try{const form=new FormData();form.append('audio',new Blob(chunks,{type:r.mimeType}),'command');const response=await tokenFetch('/api/blog-agent/voice',{method:'POST',body:form}),d:any=await response.json();if(!response.ok)throw new Error(d.error);if(mounted.current){if(d.text)onText(d.text);setNote(d.text?'인식된 문장을 확인한 뒤 전송해주세요.':'말소리를 인식하지 못했습니다. 다시 시도해주세요.');}}catch(e){if(mounted.current)setNote(e instanceof Error?e.message:'음성 인식 실패');}finally{if(mounted.current)setBusy(false);}};r.start();setRecording(true);setNote('녹음 중 · 최대 45초 · 음성은 변환을 위해 서버로 전송됩니다.');timer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},45000);}catch{release();setNote('마이크 권한을 허용해주세요. 키보드 입력도 가능합니다.');}}
 function start(){if(recording){recognition.current?.stop();if(recorder.current?.state==='recording')recorder.current.stop();return;}const Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Recognition){void record();return;}const r=new Recognition();recognition.current=r;r.lang='ko-KR';r.continuous=false;r.interimResults=false;let heard=false;r.onresult=(e:any)=>{heard=true;const text=Array.from(e.results as any[]).map((x:any)=>x[0].transcript).join(' ');onText(text);setNote('인식된 문장을 확인한 뒤 전송해주세요.');};r.onerror=(e:any)=>{release();setRecording(false);if(['not-allowed','service-not-allowed'].includes(e.error))setNote('마이크 권한을 확인해주세요. 녹음 입력도 사용할 수 있습니다.');else setNote('기본 인식에 실패했습니다. 녹음 입력을 이용해주세요.');};r.onend=()=>{if(timer.current)clearTimeout(timer.current);if(mounted.current){setRecording(false);if(!heard)setNote('인식된 말이 없습니다. 녹음 입력을 이용해주세요.');}};try{r.start();setRecording(true);setNote('듣는 중 · 브라우저의 음성 인식 서비스를 사용합니다.');timer.current=setTimeout(()=>r.stop(),45000);}catch{void record();}}
 return <div className="agent-voice"><button type="button" disabled={disabled||busy} onClick={start} aria-label={recording?'음성 입력 종료':'음성 명령 입력'} aria-pressed={recording}>{busy?<Loader2 className="spin"/>:recording?<Square/>:<Mic/>}</button><button type="button" className="agent-record-fallback" disabled={disabled||busy||recording} onClick={()=>void record()}>녹음 입력</button>{note&&<small role="status">{note}</small>}</div>;
}
