import {siteOrigin} from "../../lib/site-origin";
import ContentBody from "../../ContentBody";
import ExportButton from "./ExportButton";
import ReadingProgress from "./ReadingProgress";
import ContentTables from "../../ContentTables";
import type {Metadata} from "next";import {notFound} from "next/navigation";import PrintButton from "./PrintButton";
const PROJECT="studio-9240700230-1dd9a",KEY="AIzaSyDEpFAsf1fI65xXklKYsukAWFYw5bzaHyc",SITE=siteOrigin();
async function getContent(id:string){const r=await fetch(`https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents/publishedContents/${encodeURIComponent(id)}?key=${KEY}`,{next:{revalidate:5}});if(!r.ok)return null;const d:any=await r.json(),f=d.fields||{},s=(k:string)=>f[k]?.stringValue||"",a=(k:string)=>(f[k]?.arrayValue?.values||[]).map((x:any)=>x.stringValue);if(s("visibility")!=="public")return null;const imageIds=a("imageIds"),imageUrls=imageIds.map((_:string,index:number)=>`/api/content-images/${encodeURIComponent(id)}/${index}`);return{id,ownerId:s("ownerId"),type:s("type")||"blog",title:s("title"),keyword:s("keyword"),content:JSON.parse(s("contentJson")||"{}"),imageIds,imageUrls,publishedAt:s("publishedAt")}}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const{id}=await params,p=await getContent(id);if(!p)return{title:"콘텐츠를 찾을 수 없습니다"};return{title:`${p.title} | 허브스튜디오`,description:p.content.description||p.content.intro,alternates:{canonical:`${SITE}/content/${id}`},openGraph:{type:"article",title:p.title,description:p.content.description||p.content.intro,images:p.imageUrls[0]?[`${SITE}${p.imageUrls[0]}`]:[]}}}
function Product({p}:{p:any}) {
 const c=p.content,img=(n:number)=>n<0?null:p.imageUrls[n];
 return <main className="public-product"><header><a href="/">HUB STUDIO</a><span>PRODUCT EDITION</span><div className="public-header-actions"><ExportButton ownerId={p.ownerId}/><PrintButton/></div></header>
  <section className="product-hero"><div><small>{c.badge||"CURATED PRODUCT"}</small><h1>{p.title}</h1><ContentBody body={c.intro}/><div className="product-benefits">{c.benefits?.map((b:string,i:number)=><span key={i}><b>0{i+1}</b>{b}</span>)}</div><a className="document-jump" href="#product-information">구매 전 정보 확인 ↓</a></div>{img(0)&&<img src={img(0)} alt={p.title}/>}</section>
  <article className="product-story">{c.sections?.map((s:any,i:number)=><section id={`product-point-${i+1}`} key={i} className={img(s.imageIndex??i+1)?"with-figure":"text-only"}><div><small>POINT {String(i+1).padStart(2,"0")}</small><h2>{s.heading}</h2><ContentBody body={s.body} blocks={s.blocks}/></div>{img(s.imageIndex??i+1)&&<figure><img src={img(s.imageIndex??i+1)} alt={s.caption||s.heading}/>{s.caption&&<figcaption>{s.caption}</figcaption>}</figure>}</section>)}
   <section id="product-information" className="product-information"><h2>상품 정보와 구매 전 확인</h2><ContentTables tables={c.tables}/>{!c.tables?.length&&<p>소재·사이즈·옵션·배송 등 미제공 정보는 판매처에서 확인해주세요.</p>}</section>
   {c.faq?.length>0&&<div className="product-faq"><h2>자주 묻는 질문</h2>{c.faq.map((q:any,i:number)=><details key={i}><summary>{q.question}</summary><ContentBody body={q.answer}/></details>)}</div>}<div className="document-closing"><ContentBody body={c.closing}/></div>
  </article><footer><a href="/">허브스튜디오에서 더 보기</a></footer></main>;
}
function Ebook({p}:{p:any}) {
 const c=p.content,chapters=c.chapters||[],img=(n:number)=>n<0?null:p.imageUrls[n];
 return <main className="public-ebook"><ReadingProgress/><header><a href="/">HUB STUDIO</a><span>E-BOOK EDITION</span><div className="public-header-actions"><ExportButton ownerId={p.ownerId}/><PrintButton/></div></header>
  <section className="ebook-public-cover">{img(c.coverImageIndex??0)&&<img src={img(c.coverImageIndex??0)} alt={p.title}/>}<div><small>HUB STUDIO E-BOOK</small><h1>{p.title}</h1><p>{c.subtitle||c.description}</p><b>{c.author||"HUB STUDIO"}</b><div className="document-cover-meta"><span>{chapters.length}개 장</span><span>{new Date(p.publishedAt||p.updatedAt).toLocaleDateString("ko-KR")}</span></div></div></section>
  <article className="ebook-public-body"><section className="ebook-intro"><small>ABOUT THIS BOOK</small><h2>이 책에 대하여</h2><ContentBody body={c.intro||c.description}/></section>
   <nav id="ebook-contents" className="ebook-toc" aria-label="전자책 목차"><small>CONTENTS</small><h2>목차</h2>{chapters.map((ch:any,i:number)=><a href={`#chapter-${i+1}`} key={i}><b>{String(i+1).padStart(2,"0")}</b><span>{ch.title}</span></a>)}</nav>
   {chapters.map((ch:any,i:number)=><section className="ebook-chapter" id={`chapter-${i+1}`} key={i}><div className="chapter-copy"><small>CHAPTER {String(i+1).padStart(2,"0")}</small><h2>{ch.title}</h2>{ch.summary&&<aside className="chapter-goal"><b>이 장에서 배우는 내용</b><ContentBody body={ch.summary}/></aside>}<ContentBody body={ch.body} blocks={ch.blocks}/>{ch.keyPoints?.length>0&&<div className="chapter-points"><b>핵심 포인트·실습</b>{ch.keyPoints.map((x:string,j:number)=><span key={j}><i>✓</i>{x}</span>)}</div>}</div>{img(ch.imageIndex??-1)&&<figure><img src={img(ch.imageIndex)} alt={ch.caption||ch.title}/><figcaption>{ch.caption}</figcaption></figure>}<a className="back-to-toc" href="#ebook-contents">목차로 ↑</a></section>)}
   <ContentTables tables={c.tables}/>{c.checklist?.length>0&&<section className="ebook-checklist"><small>FINAL CHECKLIST</small><h2>마지막으로 확인하세요</h2>{c.checklist.map((x:string,i:number)=><p key={i}><i>✓</i>{x}</p>)}</section>}<div className="document-closing"><ContentBody body={c.closing}/></div>
  </article><footer><b>HUB STUDIO E-BOOK</b><a href="/">더 많은 콘텐츠 보기</a></footer></main>;
}
function Report({p}:{p:any}) {
 const c=p.content,sections=c.reportSections||[],img=(n:number)=>n<0?null:p.imageUrls[n],references=c.studioSettings?.experience||"",limitations=c.limitations||[];
 return <main className="public-report"><header><a href="/">HUB STUDIO</a><span>INSIGHT REPORT</span><div className="public-header-actions"><ExportButton ownerId={p.ownerId}/><PrintButton/></div></header>
  <section className="report-hero"><div><small>HUB STUDIO · PROFESSIONAL REPORT</small><h1>{p.title}</h1><p>{c.subtitle||c.description}</p><dl className="report-cover-meta"><div><dt>작성 주체</dt><dd>HUB STUDIO</dd></div><div><dt>발행일</dt><dd>{new Date(p.publishedAt||p.updatedAt).toLocaleDateString("ko-KR")}</dd></div><div><dt>보고 목적</dt><dd>{c.purpose||c.studioSettings?.purpose||"정보 분석 및 실행 제안"}</dd></div><div><dt>대상 독자</dt><dd>{c.studioSettings?.audience||"일반 독자"}</dd></div></dl></div>{img(0)&&<figure><img src={img(0)} alt={p.title}/><figcaption>보고서 참고 이미지 · 분석 근거와 구분</figcaption></figure>}</section>
  <article className="report-body"><section className="report-summary"><small>EXECUTIVE SUMMARY</small><h2>핵심 요약</h2><ContentBody body={c.executiveSummary}/><dl className="report-scope"><div><dt>목적</dt><dd>{c.purpose}</dd></div><div><dt>분석 범위</dt><dd>{c.scope}</dd></div></dl></section>
   <nav className="report-toc" id="report-contents" aria-label="보고서 목차"><small>CONTENTS</small><h2>목차</h2>{sections.map((s:any,i:number)=><a href={`#analysis-${i+1}`} key={i}><b>{String(i+1).padStart(2,"0")}</b><span>{s.title}</span></a>)}<a href="#report-actions"><b>실행</b><span>우선순위별 실행 계획</span></a><a href="#report-evidence"><b>근거</b><span>자료와 분석의 한계</span></a></nav>
   {c.keyFindings?.length>0&&<section className="report-key"><small>KEY FINDINGS</small><h2>주요 판단</h2><div>{c.keyFindings.map((x:any,i:number)=><article key={i}><b>{String(i+1).padStart(2,"0")}</b><h3>{x.title}</h3><ContentBody body={x.description}/><span>우선순위: {x.importance==="high"?"높음":x.importance==="medium"?"보통":"낮음"}</span></article>)}</div></section>}
   {sections.map((s:any,i:number)=><section className="report-section" id={`analysis-${i+1}`} key={i}><div><small>ANALYSIS {String(i+1).padStart(2,"0")}</small><h2>{i+1}. {s.title}</h2><ContentBody body={s.body} blocks={s.blocks}/>{s.insights?.length>0&&<aside className="report-insights"><b>핵심 시사점</b><ul>{s.insights.map((x:string,j:number)=><li key={j}>{x}</li>)}</ul></aside>}</div>{img(s.imageIndex??-1)&&<figure><img src={img(s.imageIndex)} alt={s.caption||s.title}/><figcaption>{s.caption}</figcaption></figure>}<a className="back-to-toc" href="#report-contents">목차로 ↑</a></section>)}
   <ContentTables tables={c.tables}/><section className="report-recommend" id="report-actions"><small>ACTION PLAN</small><h2>우선순위별 실행 계획</h2>{c.recommendations?.map((x:any,i:number)=><article key={i}><b>{x.priority||`P${i+1}`}</b><div><h3>{x.title}</h3><ContentBody body={x.description}/>{(x.owner||x.timeline||x.metric)&&<dl className="action-details">{x.owner&&<div><dt>담당 역할</dt><dd>{x.owner}</dd></div>}{x.timeline&&<div><dt>제안 일정</dt><dd>{x.timeline}</dd></div>}{x.metric&&<div><dt>확인 지표</dt><dd>{x.metric}</dd></div>}</dl>}</div></article>)}</section>
   <section className="report-evidence" id="report-evidence"><small>EVIDENCE & LIMITATIONS</small><h2>자료와 분석의 한계</h2>{references?<><h3>사용자가 제공한 자료</h3><ContentBody body={references}/></>:<p>별도의 참고 자료가 제공되지 않았습니다. 이 보고서는 입력한 주제와 목적을 바탕으로 만든 기획·검토안입니다.</p>}{c.evidenceNote&&<ContentBody body={c.evidenceNote}/>}<ul>{(limitations.length?limitations:["외부 자료와 수치의 사실 확인은 별도로 진행해야 합니다.","실행 전에 실제 상품 정보와 운영 조건을 확인해주세요."]).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></section><div className="document-closing"><ContentBody body={c.closing}/></div>
  </article><footer>HUB STUDIO INSIGHT REPORT</footer></main>;
}
function Blog({p}:{p:any}){const img=(n:number)=>p.imageUrls[n]||null;return <main className="public-article"><header><a href="/">HUB STUDIO</a><span>JOURNAL</span><ExportButton ownerId={p.ownerId}/></header><article><p className="pub-kicker">CURATED STORY · {p.keyword}</p><h1 title={p.title}>{p.title}</h1><div className="pub-intro"><ContentBody body={p.content.intro}/></div>{img(0)&&<img className="pub-hero" src={img(0)!} alt={p.title}/>}<div className="pub-body">{p.content.sections?.map((s:any,i:number)=><section key={s.heading}><h2>{s.heading}</h2><ContentBody body={s.body} blocks={s.blocks}/>{img(s.imageIndex??i+1)&&<figure><img src={img(s.imageIndex??i+1)!} alt={s.caption||s.heading}/>{s.caption&&<figcaption>{s.caption}</figcaption>}</figure>}</section>)}<ContentTables tables={p.content.tables}/><blockquote>{p.content.closing}</blockquote>{p.content.faq?.length>0&&<section className="pub-faq"><h2>자주 묻는 질문</h2>{p.content.faq.map((q:any)=><div key={q.question}><h3>{q.question}</h3><p>{q.answer}</p></div>)}</section>}<div className="pub-tags">{p.content.tags?.map((t:string)=><span key={t}>#{t}</span>)}</div></div></article><footer><b>HUB STUDIO</b><p>이미지에서 시작해 콘텐츠로 완성합니다.</p><a href="/">더 많은 이야기 보기</a></footer></main>}
export default async function ContentPage({params}:{params:Promise<{id:string}>}){const{id}=await params,p=await getContent(id);if(!p)notFound();return p.type==="product"?<Product p={p}/>:p.type==="ebook"?<Ebook p={p}/>:p.type==="report"?<Report p={p}/>:<Blog p={p}/>}
