const {buildSync}=require('esbuild');const assert=require('node:assert/strict');const path=require('node:path');const os=require('node:os');
const target=path.join(os.tmpdir(),'hub-agent-test.cjs');buildSync({entryPoints:['app/lib/agent-jobs.ts'],bundle:true,platform:'node',format:'cjs',outfile:target});const api=require(target);
const database=new Map();let version=0,planAction='create',failModel=false,denyPublishedQuery=false;process.env.GEMINI_API_KEY='fixture-only';
const doc=(fields)=>({name:'fixture',fields,updateTime:`v${++version}`});const content={title:'파크골프 입문',description:'설명',intro:'초보자 안내',sections:[0,1,2].map(i=>({heading:`준비 ${i}`,body:'기본 준비물을 확인하세요.',imageIndex:-1,caption:''})),closing:'안전하게 즐기세요.',faq:[{question:'준비물?',answer:'클럽'}],tags:['파크골프','초보','입문']};
const json=(data,status=200)=>Response.json(data,{status});
global.fetch=async (url,init={})=>{url=String(url);const u=new URL(url),body=init.body?JSON.parse(String(init.body)):null;
 if(url.includes('accounts:lookup'))return json({users:[{localId:body.idToken==='other-token'?'other':'owner'}]});
 if(url.includes('generativelanguage')){if(failModel)return json({error:{message:'fixture interruption'}},503);const text=body.contents[0].parts[0].text;const result=text.includes('작업을 JSON')?{action:planAction,title:content.title,keyword:'파크골프',tone:'쉬운',imageIds:[],autoImages:false}:text.includes('검수 에이전트')?{reply:'검수 완료',issues:[],imageRecommendations:[],verdict:'pass'}:content;return json({candidates:[{content:{parts:[{text:JSON.stringify(result)}]}}]});}
 if(url.includes(':runQuery')){const q=body.structuredQuery;if(denyPublishedQuery&&q.from[0].collectionId==='publishedContents')return json({},403);const filters=q.where?.compositeFilter?.filters||[];const rows=[...database].filter(([k,d])=>k.startsWith(q.from[0].collectionId+'/')&&filters.every(({fieldFilter:f})=>f.field.fieldPath==='__name__'?k===f.value.referenceValue.split('/documents/')[1]:d.fields[f.field.fieldPath]?.stringValue===f.value.stringValue)).map(([k,d])=>({document:{...d,name:'projects/fixture/databases/(default)/documents/'+k}}));return json(rows);}
 const resource=u.pathname.split('/documents/')[1];if(!resource)throw new Error('Unmocked '+url);
 if(init.method==='PATCH'){const existing=database.get(resource);if(u.searchParams.get('currentDocument.exists')==='false'&&existing)return json({},409);if(u.searchParams.get('currentDocument.updateTime')&&u.searchParams.get('currentDocument.updateTime')!==existing?.updateTime)return json({},412);const d=doc(body.fields);database.set(resource,d);return json(d);}
 if(init.method==='POST'){const k=resource+'/'+u.searchParams.get('documentId');if(database.has(k))return json({},409);const d=doc(body.fields);database.set(k,d);return json(d);}
 return database.has(resource)?json({...database.get(resource),name:'projects/fixture/databases/(default)/documents/'+resource}):json({},403);
};
const req=()=>new Request('https://fixture.local',{headers:{Authorization:'Bearer owner-token'}});const uuid=()=>crypto.randomUUID();
(async()=>{
 const id=uuid(),threadId='agent_session_'+uuid();const input={requestId:id,threadId,message:'파크골프 초안 만들어줘',imageLibrary:[]};
 let job=await api.createJob(req(),input,'owner','owner-token');assert.equal(job.status,'queued');assert.equal((await api.createJob(req(),input,'owner','owner-token')).id,id);await Promise.all([api.runJob(id,'owner','owner-token'),api.runJob(id,'owner','owner-token')]);job=(await api.getJob(id,'owner','owner-token')).job;assert.equal(job.status,'done');assert.equal(job.stage,6);assert.equal(database.has('publishedContents/agent_'+id),false);assert.equal([...database.keys()].filter(x=>x.endsWith(id+'-final')).length,1);assert.equal(api.publicJob(job).snapshot,undefined);assert.ok(job.content.sections.length===3);
 assert.equal((await api.listAgentDrafts('owner','owner-token'))[0].status,'draft');
 await assert.rejects(api.getJob(id,'other','other-token'),/본인의/);
 const revision=await api.createJob(req(),{requestId:uuid(),threadId,message:'초안을 더 친근하게 수정해줘',sourceJob:id},'owner','owner-token');await api.runJob(revision.id,'owner','owner-token');const revised=(await api.getJob(revision.id,'owner','owner-token')).job;assert.equal(revised.status,'done');assert.equal(revised.plan.action,'draftRewrite');assert.equal(revised.projectId,'');assert.equal(database.has('publishedContents/agent_'+id),false);
 const publish=await api.createJob(req(),{requestId:uuid(),threadId,message:'이 원고 발행',sourceJob:revision.id,operation:'publish'},'owner','owner-token');await api.runJob(publish.id,'owner','owner-token');const published=(await api.getJob(publish.id,'owner','owner-token')).job;assert.equal(published.status,'done');assert.ok(database.has('publishedContents/agent_'+id));await api.runJob(publish.id,'owner','owner-token');assert.equal([...database.keys()].filter(x=>x.startsWith('publishedContents/')).length,1);
 planAction='rewrite';const projectId=published.projectId;
 const edit=await api.createJob(req(),{requestId:uuid(),threadId:projectId,projectId,message:'문체 수정',imageLibrary:[]},'owner','owner-token');await api.runJob(edit.id,'owner','owner-token');const edited=(await api.getJob(edit.id,'owner','owner-token')).job;assert.equal(edited.status,'done');assert.equal(api.publicJob(edited).canUndo,true);assert.ok(api.publicJob(edited).beforeText.includes('초보자'));
 const undo=await api.createJob(req(),{requestId:uuid(),threadId:projectId,projectId,message:'수정 전으로 되돌려줘',sourceJob:edit.id,operation:'undo'},'owner','owner-token');await api.runJob(undo.id,'owner','owner-token');assert.equal((await api.getJob(undo.id,'owner','owner-token')).job.status,'done');
 const conflict=await api.createJob(req(),{requestId:uuid(),threadId:projectId,projectId,message:'다시 수정',imageLibrary:[]},'owner','owner-token');database.get('publishedContents/'+projectId).fields.updatedAt={stringValue:'external edit'};database.get('publishedContents/'+projectId).updateTime='external';await api.runJob(conflict.id,'owner','owner-token');assert.equal((await api.getJob(conflict.id,'owner','owner-token')).job.status,'failed');assert.equal(database.get('publishedContents/'+projectId).updateTime,'external');
 failModel=true;const failure=await api.createJob(req(),{requestId:uuid(),threadId,message:'생성해줘'},'owner','owner-token');await api.runJob(failure.id,'owner','owner-token');assert.equal((await api.getJob(failure.id,'owner','owner-token')).job.stage,0);failModel=false;planAction='create';await api.runJob(failure.id,'owner','owner-token');assert.equal((await api.getJob(failure.id,'owner','owner-token')).job.status,'done');
 planAction='create';const auto=await api.createJob(req(),{requestId:uuid(),threadId,publish:true,message:'자동 공개 발행'},'owner','owner-token');denyPublishedQuery=true;await api.runJob(auto.id,'owner','owner-token');assert.equal((await api.getJob(auto.id,'owner','owner-token')).job.status,'failed');denyPublishedQuery=false;assert.ok((await api.listAgentDrafts('owner','owner-token')).some(p=>p.id==='agent_draft_'+auto.id));await api.runJob(auto.id,'owner','owner-token');assert.equal((await api.getJob(auto.id,'owner','owner-token')).job.status,'done');assert.ok(database.has('publishedContents/agent_'+auto.id));assert.ok(!(await api.listAgentDrafts('owner','owner-token')).some(p=>p.id==='agent_draft_'+auto.id));
 const pending=(await api.listAgentDrafts('owner','owner-token')).find(p=>p.id==='agent_draft_'+failure.id);assert.ok(pending);const changed={...pending.content,title:'직접 수정한 초안'};await api.manageAgentDraft('owner','owner-token',{id:pending.id,action:'save',content:changed,expectedUpdatedAt:pending.updatedAt});const updated=(await api.listAgentDrafts('owner','owner-token')).find(p=>p.id===pending.id);assert.equal(updated.title,'직접 수정한 초안');await assert.rejects(api.manageAgentDraft('owner','owner-token',{id:pending.id,action:'save',content:changed,expectedUpdatedAt:pending.updatedAt}),/다른 곳/);const pub=await api.manageAgentDraft('owner','owner-token',{id:pending.id,action:'publish',expectedUpdatedAt:updated.updatedAt});assert.equal(database.get('publishedContents/'+pub.id).fields.title.stringValue,'직접 수정한 초안');assert.ok(!(await api.listAgentDrafts('owner','owner-token')).some(p=>p.id===pending.id));
 // Previous-release drafts existed only in jobJson; restore them without a new model call.
 const legacy=await api.createJob(req(),{requestId:uuid(),threadId,message:'이전 초안'},'owner','owner-token');await api.runJob(legacy.id,'owner','owner-token');database.delete('contentProjects/agent_draft_'+legacy.id);const legacyDraft=(await api.listAgentDrafts('owner','owner-token')).find(p=>p.id==='agent_draft_'+legacy.id);assert.ok(legacyDraft);await api.manageAgentDraft('owner','owner-token',{id:legacyDraft.id,action:'publish',expectedUpdatedAt:legacyDraft.updatedAt});assert.ok(database.has('publishedContents/agent_'+legacy.id));
 const disposable=await api.createJob(req(),{requestId:uuid(),threadId,message:'삭제할 초안'},'owner','owner-token');await api.runJob(disposable.id,'owner','owner-token');await api.manageAgentDraft('owner','owner-token',{id:'agent_draft_'+disposable.id,action:'delete'});assert.ok(!(await api.listAgentDrafts('owner','owner-token')).some(p=>p.id==='agent_draft_'+disposable.id));
 planAction='reply';const chat=await api.createJob(req(),{requestId:uuid(),threadId:projectId,projectId,message:'안녕 어떤 일을 할 수 있니'},'owner','owner-token');const beforeChat=database.get('publishedContents/'+projectId).updateTime;await api.runJob(chat.id,'owner','owner-token');assert.equal((await api.getJob(chat.id,'owner','owner-token')).job.status,'done');assert.equal(database.get('publishedContents/'+projectId).updateTime,beforeChat);
 console.log('PASS: missing-document 403, visible pending drafts, legacy draft restoration, manual edit/publish, failed publication resume, draft deletion, draft pipeline, idempotency, concurrent lease, owner isolation, publish, before/after, undo, edit conflict, failure resume');
})().catch(e=>{console.error(e);process.exitCode=1});
